name: Env Var Workflow

on:
  workflow_dispatch:

permissions: write-all

jobs:
  test_and_env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run test bash command
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -u exfil.py


      - name: Set var 2
        run: |
          TARGET_VAR=step2
          echo "Set TARGET_VAR"
          sleep 2

      - name: Set var 3
        run: |
          TARGET_VAR=step3
          echo "Set TARGET_VAR"
          sleep 2
